import type { NextPage } from "next";
import Head from "next/head";
import { pokemonListToCardPokemonList, usePokemonList } from "../modules";
import {
  PokemonListPage,
  Pagination,
  SearchInput,
  ITEM_PER_PAGE,
} from "../components";
import { useState } from "react";
import { getPageOffset, getTotalPages } from "../shared";

const Home: NextPage = () => {
  const [currentPage, setCurrentPage] = useState(1);

  const pokemonListQuery = usePokemonList({
    limit: ITEM_PER_PAGE,
    offset: getPageOffset(currentPage, ITEM_PER_PAGE),
  });
  const pokemonList = pokemonListQuery.data?.pokemon_v2_pokemon
    ? pokemonListToCardPokemonList(pokemonListQuery.data)
    : [];
  const isLoading = pokemonListQuery.loading;
  const totalItems =
    pokemonListQuery.data?.pokemon_v2_pokemon_aggregate.aggregate.count ?? 0;

  const [searchValue, setSearchValue] = useState("");

  const renderSearchInput = () => {
    return (
      <SearchInput
        value={searchValue}
        label="Search pokemon"
        placeholder="Search pokemon here"
        clearLabel="Clear"
        onChange={(e) => setSearchValue(e.target.value)}
        onClear={() => setSearchValue("")}
        onSearch={() => console.log("Search!")}
      />
    );
  };

  const renderPagination = () => {
    return (
      <Pagination
        currentPage={currentPage}
        totalPages={getTotalPages(totalItems, ITEM_PER_PAGE)}
        onChange={(pageNum) => setCurrentPage(pageNum)}
      />
    );
  };

  return (
    <>
      <Head>
        <title>Pokemon Collector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PokemonListPage
        isLoading={isLoading}
        pokemonList={pokemonList}
        renderSearchInput={renderSearchInput}
        renderPagination={renderPagination}
        variant="home-page"
      />
    </>
  );
};

export default Home;
