import type { NextPage } from "next";
import Head from "next/head";
import { PokemonListPage } from "../components";
import { CardPokemonItem, MY_POKEMON_LIST_STORAGE_KEY } from "../modules";
import { useLocalStorage } from "../shared";

const Home: NextPage = () => {
  const { value: myPokemonList, setValue: setMyPokemonList } = useLocalStorage<
    CardPokemonItem[]
  >(MY_POKEMON_LIST_STORAGE_KEY, []);

  const handleRelease = (pokemonId: number) => {
    setMyPokemonList((prevValue) =>
      prevValue.filter((item) => item.id !== pokemonId)
    );
  };

  return (
    <>
      <Head>
        <title>My Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PokemonListPage
        pokemonList={myPokemonList}
        myPokemonListCount={myPokemonList.length}
        variant="my-pokemon-page"
        onClickDetail={(itemId) => console.log(itemId)}
        onClickRelease={handleRelease}
      />
    </>
  );
};

export default Home;
