import { useModal, useNotificationToast } from "@sumup/circuit-ui";
import type { NextPage } from "next";
import Head from "next/head";
import {
  PokemonDetailPage,
  PokemonDetailModalContent,
  heroImageSrc,
  pokemonName,
  pokemonMoves,
  pokemonTypes,
} from "../../components";

type CatchStatus = "success" | "failed";
const catchStatus: CatchStatus[] = ["success", "failed"];
const catchPokemon = (statusList: CatchStatus[]) =>
  statusList[Math.floor(Math.random() * statusList.length)];

const PokemonDetailPageContainer: NextPage = () => {
  const { setModal } = useModal();
  const { setToast } = useNotificationToast();

  const handleSuccessCatch = () => {
    setToast({
      body: "Named the pokemon!",
    });
  };

  const handleClickCatchPokemon = () => {
    const currentStatus: CatchStatus = catchPokemon(catchStatus);
    if (currentStatus === "success") {
      setModal({
        children: (
          <PokemonDetailModalContent
            onSubmit={() => {
              handleSuccessCatch();
            }}
          />
        ),
        variant: "immersive",
        closeButtonLabel: "Close modal",
      });
    } else {
      setToast({
        body: "Failed... Trg again!",
        variant: "alert",
      });
    }
  };
  return (
    <>
      <Head>
        <title>Pokemon Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PokemonDetailPage
        heroImageSrc={heroImageSrc}
        heroImageAlt={pokemonName}
        pokemonMovesList={pokemonMoves}
        pokemonTypeList={pokemonTypes}
        onCatchPokemon={handleClickCatchPokemon}
      />
    </>
  );
};

export default PokemonDetailPageContainer;
